---
title: "Simulations Article"
author: Dries Reynders
date: 2025-06-20
number-sections: true
highlight-style: pygments
toc: true
title-block-banner-color: white
execute: 
  echo: false
  message: false
format:
  html: 
    code-fold: true
    code-line-numbers: true
    code-copy: true
    toc: true
    toc-location: left
    toc_float: true
    smooth-scroll: true
    theme: journal
    embed-resources: true
    self-contained-math: true
  pdf: 
    keep-tex: true
    geometry: 
      - top=30mm
      - left=30mm
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
library(marginaleffects)
library(survival)
library(pander)
library(kableExtra)



source("Supp_SimFunctions2.R")
```

```{r}
# Number of simulated datasets per scenario
Nsim <- 1000
# N per treatment in the simulation
Narm <- 400
# Sample size of the large N 'truth'
Nlarge <- 10^5

Nboot <- 500

```



# Simulation

- Higher X > more likely to be A=1
- Higher X > tend to have higher Y for equal A
    - Y tends to increase over time, with higher increase for A=1
- For A=0 higher X and higher Y higher chance of censoring - for A=1 the reverse
- Higher X and Higher Y lower chance of death. A=1 lower chance of death for same X and Y

```{r forarticle}

simlist <- baselist

simlist$N <- 2*Narm
simlist$tmeas <- 10

simlist$a_x_coef <- c(0, 1)

simlist$y_form <- ~ A + X + time + A*X + A*time
simlist$y_coef <- c(0, 1, 0.2, 0.2, 0.2)


simlist$c_form <- ~ A + X + Y + A*X + A*Y
simlist$c_basehaz <- 0.25/5
simlist$c_coef <- c(log(1), log(0.9), log(0.5), log(0.9), log(2.5))

simlist$d_form <- ~ A + X + Y +A*X + A*Y 
simlist$d_basehaz <- 0.5/8
simlist$d_coef <- c(log(0.7), log(0.7), log(0.8), log(1.2), log(1.3))



sim_id <- "forarticle_sim"
resfile <- sprintf("Sim_%s.rds", sim_id) 


printsimlist <- printsimlistfun(simlist)

saveRDS(simlist, sprintf("SimSettings_%s.rds", sim_id))

```


```{r child = 'PrintArgs3.Rmd'}

```

```{r}

sepresfiles <- list.files(pattern = "tempres")
resfnum <- str_remove(sepresfiles, "tempres")%>%as.numeric()

tocalc <- ! (file.exists( resfile ) | (length(sepresfiles) == Nsim))

```


```{r dosim, eval = tocalc, include=FALSE, message=FALSE}

source("Supp_do_simlong.R")

```


```{r}
#| include: false


  
  res <- list(dflarge = readRDS("dflargesep.rds"),
            truth = readRDS("truthseparate.rds"),
            #dfs = dfs,
            results = 1:Nsim%>%map_df(function(x)readRDS(glue::glue("tempres{x}.rds")))
            #,
            #sim = sim_id
            )


settings <- readRDS(sprintf("SimSettings_%s.rds", sim_id))

```


```{r}

models <- res$results%>%distinct(Setting, Method)%>%
  mutate(Sel = c(1,0,0,0,0,1,
                 1,1,1,1,1,0,
                 0,0,0,0,0,0))%>%
  filter(Sel == 1 )%>%
  mutate(Group = c("While-Alive-Effect - Baseline Censoring Only",
                   "While-Alive-Effect - Baseline Censoring Only",
                  # "While-Alive-Effect - Baseline Censoring Only",
                   "While-Alive-Effect - Adapted Methods",
                   "While-Alive-Effect - Naive Methods",
                   "While-Alive-Effect - Naive Methods",
                   "While-Alive-Effect - Naive Methods",
                   "While-Alive-Effect - Adapted Methods"),
         Label = c("IEE-IPTCW (no TV Cens)", "IEE-RegStand (no TV Cens)",
                   "IEE-IPTCW", "As Observed", "IPCW Only", "IPTW only",
                   "IEE-RegStand"))%>%
  mutate(Group = factor(Group,ordered = TRUE,
                        levels = c("While-Alive-Effect - Naive Methods",
                                   "While-Alive-Effect - Baseline Censoring Only",
                                   "While-Alive-Effect - Adapted Methods"
                                   )),
         Label = factor(Label, ordered = TRUE, 
                        levels = c("As Observed", "IPCW Only", "IPTW only",
                                   "IEE-IPTCW (no TV Cens)", "IEE-RegStand (no TV Cens)",
                                   "IEE-IPTCW", 
                                   "IEE-RegStand")))

toplot <- res$results%>%left_join(models)%>%filter(Sel == 1)

```




```{r}
#| label: fig-simres
#| fig-height: 10
#| fig-width: 6
#| fig-cap: True and mean estimated effects by method, over time 





truth <- res$truth%>%
  mutate(Type = case_when(
    
    A == "0" ~ "atnt",
    A == "1" ~ "att",
    TRUE ~ "ate"
    
  ))%>%mutate(Time = time)



nobs <- res$dflarge%>%group_by(time, A)%>%
    summarise(Nobs = mean(!Death))%>%
  bind_rows(data.frame(time = c(0,0),
                       A = c(0,1),
                       Nobs = c(1,1)))

alf <- 0.05

part1 <- toplot%>%
  group_by(Label,Group, Time)%>%summarise(QHi = quantile(Est, 1-alf/2),
                                     QLo = quantile(Est, alf/2),
                                     Est = mean(Est))

part2 <- truth%>%filter(Type == "att")%>%mutate(Time = time)

timestep <- ifelse(max(part2$Time) > 5, 2, 1)


nmeth <- nrow(models%>%filter(Sel == 1))
shapevals <-c(15, 3, 10, 17, 4, 18, 8, 7, 12 )[1:nmeth]


seltimes <- c(0,5,10)


plotcols <- c("#9ecae1", "#4292c6","#084594",
              "#74c476", "#238b45",
              "#fdae6b", #"#f16913", 
              "#8c2d04")







helptext <- expand_grid(data.frame(lab = c("Hor. Line = True value",
                               "Vert. Line = 95% Confidence Interval"),
                                x = c(0.1,0.1),
                               y = c(0.7, 0.6)),
                        part1%>%group_by(Group)%>%sample_n(1)%>%
                          ungroup()%>%select(Group)
                        )%>%
            mutate(lab = if_else(Group == "Longitudinal", lab, ""))
  
plot2 <- part2%>%
ggplot(aes(x = Time))+
# geom_point(aes(y = Eff), size = 0.5)+
  geom_line(aes(y = Eff), color = "black")+
  #geom_point(data = part1, mapping = aes(y = Est, shape = Label))+
  geom_pointrange(data = part1%>%
                  mutate(
                    QHi = case_when(
                      
                      Time %in% seltimes ~ QHi,
                      TRUE ~ NaN
                      
                    ),
                    QLo = case_when(
                      
                      Time %in% seltimes ~ QLo,
                      TRUE ~ NaN
                      
                    )
                  ), mapping = aes(ymin = QLo,
                                   ymax = QHi,
                                   y = Est,
                                   x = Time,
                                   shape = Label,
                                   colour = Label),
                position = position_dodge(0.4),
                linetype = 1)+
  geom_text(data = helptext, mapping = aes(x = x, y = y, label = lab), 
            check_overlap = TRUE, vjust = 0, hjust = 0)+
  theme_bw()+
  scale_x_continuous(breaks = seq(0,max(part2$Time), timestep), limits = c(-0.2,max(part2$Time)+0.5))+
  ylab("Estimated While-Alive Treatment Effect")+
  theme(legend.position = "bottom", legend.title = element_blank(),
        legend.text = element_text(size = 7)
        #axis.title.y = element_blank()
        )+
  scale_shape_manual(values = shapevals,guide = guide_legend(ncol = 4))+
  scale_linetype(guide = "none")+
  scale_color_manual(values = plotcols, 
                     #guide = guide_legend(override.aes = list(linetype = NA))
                     guide = guide_legend(ncol = 4))+
  facet_wrap(~Group, ncol = 1)#
 # ggtitle(expression(paste("Simulation Study: Estimated",Delta, " Y While-Alive")))#+guides(linetype = "none")

#   ggtitle(expression(paste(hat(E),"[S]")))
#   
# +
#   ggtitle(expression("E"["S*"]))
#+
#  ggtitle(expression(paste(Delta," E(Y|T>t)")))


part3 <- nobs%>%mutate(Group = "Target Population Survival Estimates")%>%
  ggplot(aes(time, Nobs, linetype = factor(A, levels = c(1,0), labels = c("Experimental", "Control"))))+
  geom_line()+
  theme_bw()+
  scale_x_continuous(limits = c(0, max(part2$Time)+0.5),
                     breaks = seq(0,max(part2$Time), timestep))+
  ylab("Standardized Survival")+
  xlab("")+
  ylim(c(0,1))+
  facet_wrap(~ Group)+
  theme(legend.position = c(0.15,0.25), legend.title = element_blank(),
        legend.text = element_text(size = 9))+
  #theme(axis.title.y = element_text(angle = 0))+
  scale_linetype(label = c("A=1", "A=0" ))+
  ggtitle(expression(paste("Simulation Study: Estimated Survival and ",Delta, "E(Y-While-Alive)")))


cowplot::plot_grid(part3, plot2, ncol = 1, 
                   rel_heights = c(1.4,3.8),
                   align = "v",
                   axis = "lr")



```

\newpage

```{r}
#| label: tbl-biassd
#| tbl-cap: Empirical bias and SD for different methods in the simulation


truth <- res$truth%>%
  mutate(Type = case_when(
    
    A == "0" ~ "atnt",
    A == "1" ~ "att",
    TRUE ~ "ate"
    
  ))%>%mutate(Time = time)



toplot%>%left_join(truth%>%filter(Type == "att"))%>%
  group_by(Label, Time)%>%
  summarise(Bias = mean(Est - Eff),
            SD = sd(Est),
            MSE = mean( (Est - Eff)^2),
            Coverage = mean(LLperc < Eff & Eff < ULperc))%>%
  #left_join(translatemethods)%>%
  mutate(across(c(Bias, SD, Coverage),~ format(round(.x,2), nsmall = 2, digits = 2) ))%>%
  select(-MSE)%>%
  pivot_longer(c(Bias, SD, Coverage), names_to = "M.", values_to = "val")%>%
  pivot_wider(names_from = Time, values_from = val, names_prefix = "T ")%>%
  group_by(Label)%>%
  mutate(RR = row_number())%>%ungroup()%>%
  mutate(Label = ifelse(RR > 1, "", as.character(Label)))%>%select(-RR)%>%
  kableExtra::kable(booktabs = TRUE)%>%
  kable_styling(font_size = 7)

```




